name: Java Spring CI/CD

on:
  push:
    branches: [feature]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Testes
        run: mvn test

      - name: Build Docker image
        run: docker build -t my-spring-app .

    # Opcional: push para Docker Hub ou outro registro, se quiser
